### ISSUE TITLE
CSSi puhul mingi a lá bootstrap?

### ISSUE THREAD

**Issue by mpoder** [krisr12/php-ruhmatoo-projekt#3]
Kas loome iseenda CSS-stiili lehe jaoks või kasutame kellegi teise oma?

- [Materialize](http://materializecss.com/about.html) - näeb välja nagu Google'i Material kujundus

- [Bootstrap](http://getbootstrap.com/) - kasutasime tunnis

- [Material Lite](https://getmdl.io/started/index.html) - sarnanse esimesega.

Palun pakkuge oma arvamust ning selle järgi saame välja mõelda.

**Comment by krisr12** [comment]
Mulle meeldks Material Lite

**Comment by elleelisa** [comment]
Mulle meeldib ka Material Lite

**Comment by mpoder** [comment]
Okei, @elleelisa ning @krisr12, teeme siis Material Lite'iga.
